### PR TITLE
Use new pull_request_target to allow commenting

### PR DESCRIPTION
**Pull request by thejcannon**
See https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

### CODE REVIEW

**Comment by mshafer-NI** [comment]
Testing?

**Comment by thejcannon** [comment]
@mshafer-NI you literally can't test this until it goes into a repo since it only operates on the code as it was in the repo where the PR is merged from 😄

**Comment by mshafer-NI** [comment]
> @mshafer-NI you literally can't test this until it goes into a repo since it only operates on the code as it was in the repo where the PR is merged from 😄

Are you not making this in your branch and then merging??

**Comment by thejcannon** [comment]
If I understand correctly, in order to test this appropriately, I'd need a fork of my fork, then check this (but maybe not @-mention everyone) into my fork, then make a PR from the fork's fork.
....I don't think I can fork my own fork 😄

**Comment by rtzoeller** [comment]
@thejcannon the answer is clearly to just have multiple GitHub accounts 😉

**Comment by DavidCurtiss** [comment]
@thejcannon but you *can* have a *branch* of a fork.

**Pull request merged**
